export default [
  require('./01_InitialSketch').default, // maybe work?
  require('./02_GCodeTest').default,
  require('./03_Arcs').default,
  require('./04_BezierScribbles').default,
  require('./05_Spiraling').default,
  require('./06_SpiralingProportional').default,
  require('./07_ConcentricCircles').default,
  require('./08_BubblesInCircle').default,
  require('./09_GridWaves').default,
  require('./10_PerlinGrid').default,
  require('./11_PerlinLines').default,
  require('./12_Tree').default,
  require('./13_MondayMaze').default,
  require('./14_Chaser').default,
  require('./15_Kaleido').default,
  require('./16_KaleidoCurve').default,
  require('./17_Perpendicularity').default,
  require('./18_Rays').default,
  require('./19_CutoutTest').default,
  require('./20_Yes').default,
  require('./21_Aeroplane').default,
  require('./22_PaleAle').default,
]
